CREATE TABLE IF NOT EXISTS players (
    player_id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name varchar(50)
        NOT NULL
        UNIQUE,

    score integer
        NOT NULL
        DEFAULT 0
        CHECK (score >= 0),

    created_at timestamptz
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS transfer_history (
    transfer_id integer
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    sender_id integer
        NOT NULL
        REFERENCES players(player_id)
        ON DELETE RESTRICT,

    receiver_id integer
        NOT NULL
        REFERENCES players(player_id)
        ON DELETE RESTRICT,

    points integer
        NOT NULL
        CHECK (points > 0),

    created_at timestamptz
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT transfer_different_players
        CHECK (sender_id <> receiver_id)
);